config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @about = 'About Us'
    @content = 'This is the about page'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <%= link_to 'Blog Site', home_path, class: "navbar-brand text-light" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', home_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Post', new_post_path, class: "nav-link text-light" %>
        </li>
      </ul>
    </div>
  </nav>

  <div class="p-5">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @about %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_with scope: :post, url: post_path(@post), method: :put, local: true do |form| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, class: 'form-control w-50' %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, class: 'form-control w-50' %>
  </p>

  <p>
    <%= form.submit class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
  <h2></h2>
  <p></p>
  <div class="card">
    <h4 class="card-header"><%= post.title %></h4>
    <div class="card-body">
      <p class="card-title"><%= post.body %></p>
      <%= link_to "Expand Post", post_path(post), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_with scope: :post, url: posts_path, local: true do |form| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, class: 'form-control w-50' %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, class: 'form-control w-50' %>
  </p>

  <p>
    <%= form.submit class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<%= link_to 'Edit Post', edit_post_path, class: "btn btn-primary" %>
<%= link_to 'Delete Post', post_path(@post), method: :delete, class: "btn btn-danger" %>

<h3 class="mt-4">Comments:</h3>
<% @post.comments.each do |comment| %>
  <p class="mt-3"><span class="font-weight-bold"><%= comment.username %>:&nbsp</span><%= comment.body %></p>
  <%= link_to 'Delete Comment', [comment.post, comment], method: :delete, class: 'text-danger' %>
<% end %>

<h3 class="mt-4">Add Comment</h3>
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :username %><br>
    <%= form.text_field :username, class: 'form-control w-50' %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, class: 'form-control w-50' %>
  </p>
  <p>
    <%= form.submit class: 'btn btn-primary' %>
  </p>
<% end %>